### ISSUE TITLE
docker?

### ISSUE THREAD

**Issue by alexlib** [AssaSch/openpiv-saas#2]
@AssaSch - can we use Docker for the installation? I have some experience with it, e.g. 
http://github.com/alexlib/Dockerfiles

**Comment by AssaSch** [comment]
for the installation on the server? yes we can.
i will add the Dockerfile to the repo.

**Comment by alexlib** [comment]
something like this is our future:

https://medium.com/postman-engineering/deploying-a-scalable-web-application-with-docker-and-kubernetes-a5000a06c4e9
